blank_issues_enabled: false
contact_links:
  - name: Hummingbot Discord
    url: https://discord.gg/hummingbot
    about: Discord is the main hub for the Hummingbot community. Join to chat with other users and developers.
