name: Script Design
description: Use this template to create your Demo Day script
title: "Script Design"
labels: design
body:
 - type: markdown
   attributes:
     value: |
       ## How to Use this Template
       
       * Watch the Design and Contribute section in [Hummingbot Botcamp Module 1](https://botcamp.hummingbot.org/p/1-basic-training-free-preview)
       * Try to fill this out before writing code - it will save you time and effort in the long run!
       * See [here] for an example template

 - type: markdown
   attributes:
     value: |
      ## Strategy Description

 - type: textarea
   id: type
   attributes:
     label: type
     description: What type of strategy are you creating?
     placeholder:  Market making, mean reversion, arbitrage, hedging, rebalancing, etc...
   validations:
     required: true

 - type: textarea
   id: environment
   attributes:
     label: environment
     description: What assumptions are you making about market conditions that will allow this strategy to work?
     placeholder: Market conditions, exchange used, transaction costs, target user, etc...
   validations:
     required: true

 - type: textarea
   id: description
   attributes:
     label: description
     description: Describe how your script will work
     placeholder: List each step that the script will take to execute the strategy
   validations:
     required: true

 - type: markdown
   attributes:
     value: |
      ## Script Logic

 - type: textarea
   id: inputs
   attributes:
     label: Inputs
     description: What are the variables that the user will need to define to run the script?
     value: |
       1. 
       2. 
       3. 
       4.
       5.

 - type: textarea
   id: status
   attributes:
     label: Format Status
     description: What information should be displayed when you run the `status` command?
     value: |
       1. 
       2. 
       3. 
       4.
       5.

 - type: textarea
   id: events
   attributes:
     label: Events
     description: What events does the script listen for and how does it respond to them?
     value: |
       1. 
       2. 
       3. 
       4.
       5.

 - type: markdown
   attributes:
     value: |
      ## Script Logic
      Provide an image or link to a flowchart that describes the logic executed during the `on_tick` function.
      Suggested tools: [Miro](https://miro.com/), [Lucidchart](https://www.lucidchart.com/pages/)

 - type: textarea
   id: flowchart
   attributes:
     label: Logic Flowchart
     description: Provide an image or link to a flowchart that describes the logic executed during the `on_tick` function.
   validations:
     required: true
